spring.application.name=musicroom

spring.datasource.url=jdbc:postgresql://localhost:5432/musicroom
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.flyway.enabled=false

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.try-it-out-enabled=true