spring.application.name=musicroom

spring.datasource.url=jdbc:postgresql://localhost:5432/musicroom
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true