spring.application.name=musicroom

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/musicroom
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Flyway — désactivé pour l'instant
spring.flyway.enabled=false

# JWT Configuration
jwt.secret=your-super-secret-jwt-key-change-this-in-production-at-least-32-characters-long-for-security
jwt.expiration.access=600000
jwt.expiration.refresh=604800000

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aboubakerfanti1@gmail.com
spring.mail.password=flal huwm skdv thme
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Email sender info
app.mail.from=your-email@gmail.com
app.mail.from.name=Music Room